version: "3.9"

services:
  postgresql:
    image: postgres:15
    container_name: uts_postgresql
    restart: unless-stopped
    environment:
      POSTGRES_DB: uts_db
      POSTGRES_USER: uts_user
      POSTGRES_PASSWORD: uts_password
    networks:
      uts_internal_net:
        ipv4_address: 172.28.15.10
    ports:
      - "IP_ZEROTIER:5415:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    container_name: uts_adminer
    restart: unless-stopped
    depends_on:
      - postgresql
    networks:
      uts_internal_net:
        ipv4_address: 172.28.15.20


  nginx:
    image: nginx:alpine
    container_name: uts_nginx
    restart: unless-stopped
    depends_on:
      - adminer
    ports:
      - "8015:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      uts_internal_net:
        ipv4_address: 172.28.15.30

networks:
  uts_internal_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.15.0/24

volumes:
  pg_data:

